EjsU7-SG/Controllers/EditarPersonaController.cs
using Microsoft.AspNetCore.Mvc;
using EjsU7_SG.Models.ViewModel;
using EjsU7_SG.Models.Entidades;

namespace EjsU7_SG.Controllers
{
    public class EditarPersonaController : Controller
    {
        /// <summary>
        /// Action result para la vista EditarPersona
        /// A la vista se le envía una ViewModel clsPersonaDepartamento, que contiene una lista de personas con departamentos
        /// y otra de departamentos
        /// Post: Siempre devuelve algo
        /// </summary>
        /// <returns>Devuelve la vista EditarPersona</returns>
        public IActionResult EditarPersona()
        {
            return View(new clsPersonaDepartamento());
        }
        [HttpPost]
        public IActionResult GuardarPersona(clsPersona persona)
        {
            return View();
        }
    }
}

EjsU7-SG/Views/EditarPersona/EditarPersona.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model EjsU7_SG.Models.ViewModel.clsPersonaDepartamento


@Html.ActionLink("Lista de personas", "listadoPersonas", "Home")
@Html.ActionLink("Página Principal", "Index", "Home")

<!--Formulario-->
<div class="text-center">
    @using (Html.BeginForm("GuardarPersona", "EditarPersona", FormMethod.Post))
    {
        <input type="text" name="id" value="@Model.Id" hidden>
        <br />
        <br />
        <label>Nombre: </label>
        @Html.TextBoxFor(persona => persona.Nombre)
        <br />
        <br />
        <label>Apellidos: </label>
        @Html.TextBoxFor(persona => persona.Apellidos)
        <br />
        <br />
        <label for="departamentos">Departamento: </label>
        <select name="IdDepartamento">
            @{
                foreach (var departamento in Model.ListaDepartamentos)
                {
                    if (Model.IdDepartamento == departamento.IdDepartamento)
                    {
                        <option selected="@departamento.NombreDepartamento" value="@departamento.IdDepartamento">@departamento.NombreDepartamento</option>
                    }
                    else
                    {
                        <option value="@departamento.IdDepartamento">@departamento.NombreDepartamento</option>
                    }
                }
            }
        </select>
        <br />

        <br />
        <button type="submit">Guardar</button> 
    }
    
</div>

EjsU7-SG/Views/EditarPersona/GuardarPersona.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>
    Persona guardada correctamente
</h1>